### ISSUE TITLE
Master VCF paths

### ISSUE THREAD

**Issue by b-tierney** [dsarov/SPANDx#21]
Hi -- it seems that when running the Master VCF script at the last step, at least in my environment, the path to the reference is not correctly recorded -- it's not including the picard Dict or any of the other files necessary to run the gatk command. Here is the issue:

Command:

gatk VariantFiltration -R type_strain.fasta -O out.filtered.vcf -V out.vcf     --cluster-size 3 -window 10     -filter "QD < 10.0" --filter-name "QDFilter"     -filter "MQ < 30.0" --filter-name "MQFilter"     -filter "FS > 60.0" --filter-name "HaplotypeScoreFilter"

Error:

A USER ERROR has occurred: Fasta index file file:///path/to/working/dir/type_strain.fasta.fai for reference file:///path/to/working/dir/type_strain.fasta does not exist. Please see http://gatkforums.broadinstitute.org/discussion/1601/how-can-i-prepare-a-fasta-file-to-use-as-reference for help creating it.

Is this something with my environment, or do the paths to the index reference (in the work dirs) need to be updated? Note that if I manually create the samtools index, it gives a similar error looking for the dict file, and if I create that, it gives another one looking for the vcf.

Also, on a totally unrelated note, the native install seems to call python1.6 -- this led to gatk errors. I had to switch the shebang in the gatk conda environment script (e.g. /~/miniconda3/envs/spandx/bin/gatk) to explicitly point to python3 instead of python

**Comment by dsarov** [comment]
Hi Braden,

That is a bit odd. Usually all the indices and dict files are made as part of the workflow and they all should link through with each step. let me read through the code and see if there is something wrong. The port to nextflow has been a bit buggy so there could be issues.

Cheers,

Derek

**Comment by dsarov** [comment]
The file processing looks generally okay in that spot - lines 899 to 907 of main.nf. Could you let me know your initial SPANDx command? I'm running a test at the moment so should be able to double check the error shortly.

--------------------

  process Master_vcf {
    label "master_vcf"
    publishDir "./Outputs/Master_vcf", mode: 'copy', overwrite: true

    input:
    file("*.raw.gvcf") from gvcf_files.collect()
    file reference from reference_file
    file reference_fai from ref_fai_ch1
    file reference_dict from ref_dict_ch1
---------------

**Comment by b-tierney** [comment]
Hi Derek -- thanks so much for the quick response.

It sounds like it's got to be something on my end...the command I'm running is just a simple test with 1 file:

nextflow run dsarov/spandx --ref type_strain.fasta

Rerunning this now with a clean install and will pass along the the stdout when it's done.

input files are just named as such:

SRR5511230_1.fastq.gz  SRR5511230_2.fastq.gz

**Comment by b-tierney** [comment]
Hm maybe this helps? Maybe I'm misinterpreting the error -- but regardless it does appear to be a path issue...thanks again for the help here. So excited to get this all working
[stdout.txt](https://github.com/dsarov/SPANDx/files/8972909/stdout.txt)

**Comment by dsarov** [comment]
Hi Braden,

Could you check what files you have in ./work/16/5c0fdc....  directory? That directory should have the output from the IndexReference process.

There should be both the reference dict and fai files but I think there might be a problem with creating these files that means they aren't available for subsequent commands. 

Could you e-mail me your type_strain.fasta file too? I'm wondering if there is a problem with that file that's causing the issue. My work address is dsarovich@usc.edu.au

Thanks!

Derek

**Comment by b-tierney** [comment]
Here are the output sin that directory:

./work/16/5c0fdc900d6e5364e5f6ec11294b31/
./work/16/5c0fdc900d6e5364e5f6ec11294b31/ref.amb
./work/16/5c0fdc900d6e5364e5f6ec11294b31/type_strain.fasta.fai
./work/16/5c0fdc900d6e5364e5f6ec11294b31/ref.ann
./work/16/5c0fdc900d6e5364e5f6ec11294b31/type_strain.dict
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.command.begin
./work/16/5c0fdc900d6e5364e5f6ec11294b31/ref.sa
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.command.out
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.command.sh
./work/16/5c0fdc900d6e5364e5f6ec11294b31/ref.pac
./work/16/5c0fdc900d6e5364e5f6ec11294b31/ref.bwt
./work/16/5c0fdc900d6e5364e5f6ec11294b31/type_strain.fasta.bed
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.command.err
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.command.run
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.exitcode
./work/16/5c0fdc900d6e5364e5f6ec11294b31/.command.log
./work/16/5c0fdc900d6e5364e5f6ec11294b31/type_strain.fasta

Looks like everything is in there...thanks again for the all the help. Emailing ref now! 

Braden

**Comment by b-tierney** [comment]
Other errors in that stderr file include the out.vcf file being unfindable -- could that also be at the heart of some path issue?

**Comment by b-tierney** [comment]
Closing this out -- per our conversation via email, it seems this error arose form using too few samples in my test run. Tried rerunning with 3 instead of 1, and it ran to completion! Thanks again.
